apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frames2flow-deployment
  labels:
    app: frames2flow
spec:
  replicas: 4
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: frames2flow
    spec:
      containers:
      - name: frames2flow
        image: kikko/frames2flow
        imagePullPolicy: Always
        ports:
          - containerPort: 50051
        resources:
          limits:
            cpu: 1
          requests:
            cpu: 0.5
---
apiVersion: v1
kind: Service
metadata:
  name: frames2flow-service
spec:
  type: NodePort
  ports:
  - port: 50051
    nodePort: 30003
    targetPort: 50051
  selector:
    app: frames2flow
